/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

/**
 *
 * @author ThiagodaSilvaCarneir
 */
public class telaPrincip extends javax.swing.JFrame {

    /**
     * Creates new form telaPrincip
     */
    public telaPrincip() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        Atendimento = new javax.swing.JMenu();
        agendamento = new javax.swing.JMenu();
        Cadastro = new javax.swing.JMenu();
        Veterinario = new javax.swing.JMenu();
        Medicamentos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Clinica Veterinaria Soteropolitano");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1131, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );

        Atendimento.setText("Atendimento");
        Atendimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AtendimentoMouseClicked(evt);
            }
        });
        menu.add(Atendimento);

        agendamento.setText("Agendamento");
        agendamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agendamentoMouseClicked(evt);
            }
        });
        menu.add(agendamento);

        Cadastro.setText("Cadastro");
        Cadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastroMouseClicked(evt);
            }
        });
        menu.add(Cadastro);

        Veterinario.setText("Veterinarios");
        Veterinario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VeterinarioMouseClicked(evt);
            }
        });
        menu.add(Veterinario);

        Medicamentos.setText("Medicamentos");
        Medicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MedicamentosMouseClicked(evt);
            }
        });
        menu.add(Medicamentos);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AtendimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AtendimentoMouseClicked
           new Atendimento().setVisible(true);
           
    }//GEN-LAST:event_AtendimentoMouseClicked

    private void agendamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agendamentoMouseClicked
        new Agendamento().setVisible(true);
    }//GEN-LAST:event_agendamentoMouseClicked

    private void CadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastroMouseClicked
            new Cadastro().setVisible(true);       
    }//GEN-LAST:event_CadastroMouseClicked

    private void VeterinarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VeterinarioMouseClicked
        new Veterinario().setVisible(true);
    }//GEN-LAST:event_VeterinarioMouseClicked

    private void MedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedicamentosMouseClicked
       new Medicamentos().setVisible(true);
    }//GEN-LAST:event_MedicamentosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaPrincip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaPrincip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaPrincip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaPrincip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaPrincip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Atendimento;
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenu Medicamentos;
    private javax.swing.JMenu Veterinario;
    private javax.swing.JMenu agendamento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menu;
    // End of variables declaration//GEN-END:variables
}
