/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Jframes;

import bancoDados.acessoDados;

/**
 *
 * @author ts930
 */
public class Veterinario extends javax.swing.JFrame {
 acessoDados acessoDados = new acessoDados();
    /**
     * Creates new form Veterinario
     */
    public Veterinario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablepVeterinario = new javax.swing.JTabbedPane();
        paneVet = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaVet = new javax.swing.JList<>();
        btCadastrar = new javax.swing.JButton();
        btCancSair = new javax.swing.JButton();
        buscarVet = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        PaneCadVET = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfNomeVet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfEspecialidadeVet = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        brCancel = new javax.swing.JButton();
        cbAtivo = new javax.swing.JCheckBox();
        tfRegiVet = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Veterinarios");

        TablepVeterinario.setEnabled(false);

        listaVet.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaVet);

        btCadastrar.setText("Cadastrar Veterinarios");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btCancSair.setText("Cancelar/Sair");
        btCancSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancSairActionPerformed(evt);
            }
        });

        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneVetLayout = new javax.swing.GroupLayout(paneVet);
        paneVet.setLayout(paneVetLayout);
        paneVetLayout.setHorizontalGroup(
            paneVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneVetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneVetLayout.createSequentialGroup()
                        .addComponent(buscarVet, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 339, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneVetLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btCancSair, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        paneVetLayout.setVerticalGroup(
            paneVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneVetLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(paneVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarVet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneVetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancSair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TablepVeterinario.addTab("Veterinarios", paneVet);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Nome:");

        tfNomeVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeVetActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Registro:");

        tfEspecialidadeVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEspecialidadeVetActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Especialidade:");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        brCancel.setText("Cancelar");
        brCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brCancelActionPerformed(evt);
            }
        });

        cbAtivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbAtivo.setSelected(true);
        cbAtivo.setText("Ativo");

        try {
            tfRegiVet.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("AA  #####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfRegiVet.setText("ex: BA 58459");

        javax.swing.GroupLayout PaneCadVETLayout = new javax.swing.GroupLayout(PaneCadVET);
        PaneCadVET.setLayout(PaneCadVETLayout);
        PaneCadVETLayout.setHorizontalGroup(
            PaneCadVETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaneCadVETLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(brCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(PaneCadVETLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(PaneCadVETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PaneCadVETLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNomeVet, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2))
                    .addGroup(PaneCadVETLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfEspecialidadeVet, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PaneCadVETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbAtivo)
                    .addComponent(tfRegiVet, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        PaneCadVETLayout.setVerticalGroup(
            PaneCadVETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PaneCadVETLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PaneCadVETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfNomeVet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tfRegiVet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(PaneCadVETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfEspecialidadeVet, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAtivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(PaneCadVETLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        TablepVeterinario.addTab("Cadastro Veterinairos", PaneCadVET);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TablepVeterinario)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TablepVeterinario, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed

        TablepVeterinario.setSelectedIndex(1);
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btCancSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancSairActionPerformed

    private void tfNomeVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeVetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeVetActionPerformed

    private void tfEspecialidadeVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEspecialidadeVetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEspecialidadeVetActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        String ativo = "1";
        if(!cbAtivo.isSelected()){
            ativo = "0";
        }else{}
        String inserirvet = "INSERT INTO veterinario (registro_vet, nome_vet, especialidade_vet, ativo_vet) VALUES ('"+tfRegiVet.getText().toString()+"','"+
        tfNomeVet.getText().toString()+"','" +tfEspecialidadeVet.getText().toString()+"','"+ativo+"')";
        acessoDados.inserirBd(inserirvet);//inset animal
        limpartf();
        TablepVeterinario.setSelectedIndex(0);
    }//GEN-LAST:event_btSalvarActionPerformed

    private void brCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brCancelActionPerformed
        TablepVeterinario.setSelectedIndex(0);
        limpartf();
    }//GEN-LAST:event_brCancelActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        String SelectVet = "SELECT registro_vet,nome_vet,especialidade_vet,ativo_vet  FROM veterinario WHERE (nome_vet LIKE '%') OR (registro_vet LIKE '%' ) ";
        acessoDados.mostarDadosJlist(listaVet,SelectVet);
        
        //listaVet.add()
    }//GEN-LAST:event_btBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Veterinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Veterinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneCadVET;
    private javax.swing.JTabbedPane TablepVeterinario;
    private javax.swing.JButton brCancel;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btCancSair;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField buscarVet;
    private javax.swing.JCheckBox cbAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaVet;
    private javax.swing.JPanel paneVet;
    private javax.swing.JTextField tfEspecialidadeVet;
    private javax.swing.JTextField tfNomeVet;
    private javax.swing.JFormattedTextField tfRegiVet;
    // End of variables declaration//GEN-END:variables

    
    public void limpartf(){
        tfEspecialidadeVet.setText("");
        tfNomeVet.setText("");
        tfRegiVet.setText("");
        cbAtivo.setSelected(true);
    }











}
